openapi: 3.0.0
info:
  title: sample-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/user/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: ユーザー情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    format: int64
                    example: '100'
                    minimum: 0
                  last_name:
                    type: string
                    example: 圭一
                    minLength: 1
                    maxLength: 50
                  email:
                    type: string
                    format: email
                    example: keiichi-honma@two2.jp
                    minLength: 1
                    maxLength: 255
                required:
                  - userId
      operationId: get-user-userId
      parameters:
        - schema:
            type: integer
          in: query
          name: userId
          description: 取得したいユーザーのID
          required: true
    patch:
      summary: ユーザー情報更新
      tags: []
      responses: {}
      operationId: patch-user-userId
      parameters:
        - schema:
            type: integer
          in: query
          name: userId
          required: true
          description: 更新したいユーザーのID
      description: ''
    delete:
      summary: ユーザー情報削除
      tags: []
      responses: {}
      operationId: delete-user-userId
      parameters:
        - schema:
            type: integer
          in: query
          name: userId
          description: 削除したいユーザーのID
          required: true
components:
  schemas: {}
